### ISSUE TITLE
Rename transform to geom_transform

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/udf-catalogue#10]
When we endorse `gavo_transform` as ` ivo_transform` can we rename it to `ivo_geom_transform`, otherwise it makes it harder to have another type of `transform` in the `ivo` namespace in the future.

**Comment by jontxu** [comment]
Fair point. I think it should be done for the next version.

Perhaps we ought to add an extra section or appendix containing some rules and/or guidelines for providers when naming functions, such as, for instance:

* Using unambiguous names to avoid the aforementioned `ivo_transform` issues
* Have some sort of agreements on terminology: e.g., picking one or more out of `geo`/`geom`/`geometry`
* Aliases: `ivo_geom_transform` = `ivo_geometry_transform` (gives users a bit of leeway)

**Comment by mbtaylor** [comment]
I think I'd prefer `ivo_sky_transform` on the grounds that this is intended for sky coordinate systems, and other coordinate system types exist.  But I admit that the term "geometry" is used in ADQL to mean "sky geometry", so maybe saying geo/geom/geometry is more consistent.

**Comment by jontxu** [comment]
> I think I'd prefer `ivo_sky_transform` on the grounds that this is intended for sky coordinate systems, and other coordinate system types exist. But I admit that the term "geometry" is used in ADQL to mean "sky geometry", so maybe saying geo/geom/geometry is more consistent.

Extending on the alias point I made above, how feasible (and sensible) would it be to allow having both signatures for the same UDF (at least as a temporary measure)? By having multiple `<form>` tags defined in the language features in the TAP capabilities endpoint, a user querying a given service (through TOPCAT, PyVO, or the website itself) could get something like below:

> **`ivo_geo_transform(from_sys TEXT, to_sys TEXT, geo GEOMETRY) -> GEOMETRY`** 
> **`ivo_sky_transform(from_sys TEXT, to_sys TEXT, geo GEOMETRY) -> GEOMETRY`**
> **`ivo_geometry_transform(from_sys TEXT, to_sys TEXT, geo GEOMETRY) -> GEOMETRY`**
>
> The function transforms ADQL geometries between various reference systems. geo can be a `POINT`, a `CIRCLE`, or a `POLYGON`, and the function will return a geometry of the same type. In the current implementation, from_sys and to_sys must be literal strings (i.e., they cannot be computed through expressions or be taken from database columns). All transforms are just simple rotations, which is only a rough approximation to the actual relationships between reference systems (in particular between FK4 and ICRS-based ones). Note that, in particular, the epoch is not changed (i.e., no proper motions are applied). We currently support the following reference frames: `ICRS`, `FK5` (which is treated as ICRS), `FK4` (for B1950. without epoch-dependent corrections), `GALACTIC`. Reference frame names are case-sensitive.**

There could be cases where two services implement the same functionality with different (albeit similar) UDF names. Having aliases could be some sort of compromise. Or conversely, a unified name could be agreed on through discussion on this repository (by opening an issue and/or a pull request).

**Comment by msdemlei** [comment]
PR #15 already has ivo_geom_transform, and both reference implementors (ESAC and DaCHS) agree that's a good idea; at least DaCHS has already performed the renaming.  I'll close this; if anyone actually feels strongly about having sky in there, please reopen (but I'll argue that it's spherical geometry and hence not necessarily sky what we're talking about here).

**Comment by gmantele** [comment]
@jontxu , sorry for commenting so late.

> Extending on the alias point I made above, how feasible (and sensible) would it be to allow having both signatures for the same UDF (at least as a temporary measure)? By having multiple `<form>` tags defined in the language features in the TAP capabilities endpoint, a user querying a given service (through TOPCAT, PyVO, or the website itself) could get something like below:
> 
> > **`ivo_geo_transform(from_sys TEXT, to_sys TEXT, geo GEOMETRY) -> GEOMETRY`**
> > **`ivo_sky_transform(from_sys TEXT, to_sys TEXT, geo GEOMETRY) -> GEOMETRY`**
> > **`ivo_geometry_transform(from_sys TEXT, to_sys TEXT, geo GEOMETRY) -> GEOMETRY`**

Although it is a nice attention to make compromise, I have to say that allowing multiple forms for the same function is, according to me, the best way to confuse users. So, I am not really in favor of something like this in the future. We should provide only one form for each function. The simpler the better.

**Comment by jontxu** [comment]
> Although it is a nice attention to make compromise, I have to say that allowing multiple forms for the same function is, according to me, the best way to confuse users. So, I am not really in favor of something like this in the future. We should provide only one form for each function. The simpler the better.

I agree. The compromise is a temporary solution, and was never intended as definitive... as long as a consensus were reached.

In any case, there could be an issue whenever a provider were to rename its functions from `foo_` to `ivo_`: some queries, automatised or not, would not work anymore and therefore users would need to be informed about the change. Either by returning a somewhat helpful error message  (“function A is deprecated, use B instead”) or by other means... 

I guess this is out of our scope but might be worth discussing nevertheless. These kind of terminology clashes are bound to happen, but the less the better.
