### ISSUE TITLE
Preview link is broken

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/udf-catalogue#9]
The link to the auto-generated preview returns a not found error.
https://github.com/ivoa-std/udf-catalogue/releases/download/auto-pdf-preview/udf-catalogue-draft.pdf

**Comment by msdemlei** [comment]
I don't think this document needs the expensive CI runs (and it certainly doesn't need cross-domain links): Reviews should normally be done once there are PENs on ivoa.net.  So, for now I've removed the link, which shouldn't have been there to begin with.

If someone feels there should be CI on this, feel free to do a PR as per ivoatexDoc.
